project_id = "ademkmutqadxocfuypnk"

[functions.predict]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.business-search]
verify_jwt = false

[functions.sentiment]
verify_jwt = false

[functions.predict-schema]
verify_jwt = false
